pipeline { 
    agent any
    parameters { 

        text(name: 'Command', description: "Helm or Kubectl CLI to deploy/update/delete apps in Non-Prod EKS")

    } 
    stages {
        stage('Build'){
            steps{
                echo "Hello"
            }  
         }
     }
}
