### TEST TEMPLATE ONLY (works on AWS only)
###
### This template serves as an example how to deploy a very simple NFS server providing persistent volumes
### in read write many mode (as all the application nodes require to access the shared home from one persistent volume).
### More visual representation can be found in official kubernetes repository:
### https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs

### For NFS server you should be using fast underlying storage as it will directly impact performance for your Bitbucket
### instance. Please see documentation specific for your kubernetes cluster infrastructure.
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io1-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    build.identifier: test-nfs-server
    build.component: nfs-server-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  encrypted: "true"
  fsType: ext4


### PersistentVolumeClaim will dynamically create the persistent volume based on the defined storageClassName.
### This will spare you the manual step when you need to create the underlying volume manually and then
### define PersistentVolume for it. You might still prefer that approach as it will give you more control over
### your data
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-server-data-pvc
  labels:
    build.identifier: test-nfs-server
    build.component: nfs-server-pvc
spec:
  storageClassName: io1-fast # defined above
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # make sure you have enough space for your shared home

---

kind: Service
apiVersion: v1
metadata:
  name: test-nfs-server
  labels:
    build.identifier: test-nfs-server
    build.component: nfs-server-service
spec:
  type: LoadBalancer
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: test-nfs-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nfs-server
  labels:
    build.identifier: test-nfs-server
    build.component: nfs-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: test-nfs-server
  template:
    metadata:
      labels:
        role: test-nfs-server
    spec:
      containers:
        - name: test-nfs-server
          image: atlassian/nfs-server-test:latest # this is just a testing image not recommended for any other use case
          imagePullPolicy: Always
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_MODULE
          volumeMounts:
            - name: test-nfs-server-data-pvc
              mountPath: /srv/nfs
            - name: test-nfs-server-conf
              mountPath: /etc/exports.d/
          resources:
            requests:
              cpu: 2000m
              memory: 4G
      terminationGracePeriodSeconds: 60
      volumes:
        - name: test-nfs-server-data-pvc
          persistentVolumeClaim:
            claimName: test-nfs-server-data-pvc
        - name: test-nfs-server-conf
          configMap:
            name: test-nfs-server-conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-nfs-server-conf
  labels:
    build.identifier: test-nfs-server
    build.component: nfs-server-configmap
data:
  share.exports: |-
    /srv/nfs *(rw,subtree_check,fsid=0,no_root_squash)
