# TEST TEMPLATE ONLY
#
# This templates serves only as a testing tool to verify accessibility of the NFS server.
# To test the storage from NFS server, you need to create a volume that is using the nfs definition and references
# the NFS server.
#
# You are required to override spec.volumes.nfs.server property and replace it with the address of the NFS server.
# For more detailed configuration see https://kubernetes.io/docs/concepts/storage/volumes/#nfs
---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: "/srv/nfs"
          name: shared-home-nfs

  volumes:
    - name: shared-home-nfs
      nfs:
        path: /srv/nfs
        server:  # this needs to be provided manually
