apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 0.12.0
appVersion: 8.13.7-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Jira DC
  - Atlassian
home: https://www.atlassian.com/software/jira
icon: https://atlassian-labs.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Defining the following values in the helpers template for each chart, to allow template overrides
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/173
    - kind: fixed
      description: Wording improvement for warning in NOTES when PV is not used
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/199
    - kind: fixed
      description: Improve readability of values.yaml
      links:
      - name: Github PR
        url: https://github.com/atlassian-labs/data-center-helm-charts/pull/182